//probably create one file with ruValue and enValue???
//add event.code?
export const englishKeyboardArray = [
   {
      row: 0,
      value: 'Esc',
      pressedShift: '',
      capsLocked: 'Esc',
      keycode: '27',
      code: 'Escape',
   },
   {
      row: 0,
      value: '`',
      pressedShift: '~',
      capsLocked: '`',
      keycode: '48',
      code: 'Backquote',
   },
   {
      row: 0,
      value: '1',
      pressedShift: '!',
      capsLocked: '1',
      keycode: '49',
      code: 'Digit1',
   },
   {
      row: 0,
      value: '2',
      pressedShift: '@',
      capsLocked: '2',
      keycode: '50',
      code: 'Digit2',
   },
   {
      row: 0,
      value: '3',
      pressedShift: '#',
      capsLocked: '3',
      keycode: '51',
      code: 'Digit3',
   },
   {
      row: 0,
      value: '4',
      pressedShift: '$',
      capsLocked: '4',
      keycode: '52',
      code: 'Digit4',
   },
   {
      row: 0,
      value: '5',
      pressedShift: '%',
      capsLocked: '5',
      keycode: '53',
      code: 'Digit5',
   },
   {
      row: 0,
      value: '6',
      pressedShift: '^',
      capsLocked: '6',
      keycode: '54',
      code: 'Digit6',
   },
   {
      row: 0,
      value: '7',
      pressedShift: '&',
      capsLocked: '7',
      keycode: '55',
      code: 'Digit7',
   },
   {
      row: 0,
      value: '8',
      pressedShift: '*',
      capsLocked: '8',
      keycode: '56',
      code: 'Digit8',
   },
   {
      row: 0,
      value: '9',
      pressedShift: '(',
      capsLocked: '9',
      keycode: '57',
      code: 'Digit9',
   },
   {
      row: 0,
      value: '0',
      pressedShift: ')',
      capsLocked: '0',
      keycode: '48',
      code: 'Digit0',
   },
   {
      row: 0,
      value: '-',
      pressedShift: '_',
      capsLocked: '-',
      keycode: '189',
      code: 'Minus',
   },
   {
      row: 0,
      value: '=',
      pressedShift: '+',
      capsLocked: '=',
      keycode: '187',
      code: 'Equal',
   },
   {
      row: 0,
      value: 'delete',
      pressedShift: '',
      capsLocked: 'delete',
      keycode: '8',
      code: 'Backspace',
   },
   {
      row: 1,
      value: 'Tab',
      pressedShift: '',
      capsLocked: 'Tab',
      keycode: '9',
      code: 'Tab',
   },
   {
      row: 1,
      value: 'q',
      pressedShift: 'Q',
      capsLocked: 'Q',
      keycode: '81',
      code: 'KeyQ',
   },
   {
      row: 1,
      value: 'w',
      pressedShift: 'W',
      capsLocked: 'W',
      keycode: '87',
      code: 'KeyW',
   },
   {
      row: 1,
      value: 'e',
      pressedShift: 'E',
      capsLocked: 'E',
      keycode: '69',
      code: 'KeyE',
   },
   {
      row: 1,
      value: 'r',
      pressedShift: 'R',
      capsLocked: 'R',
      keycode: '82',
      code: 'KeyR',
   },
   {
      row: 1,
      value: 't',
      pressedShift: 'T',
      capsLocked: 'T',
      keycode: '84',
      code: 'KeyT',
   },
   {
      row: 1,
      value: 'y',
      pressedShift: 'Y',
      capsLocked: 'Y',
      keycode: '89',
      code: 'KeyY',
   },
   {
      row: 1,
      value: 'u',
      pressedShift: 'U',
      capsLocked: 'U',
      keycode: '85',
      code: 'KeyU',
   },
   {
      row: 1,
      value: 'i',
      pressedShift: 'I',
      capsLocked: 'I',
      keycode: '73',
      code: 'KeyI',
   },
   {
      row: 1,
      value: 'o',
      pressedShift: 'O',
      capsLocked: 'O',
      keycode: '79',
      code: 'KeyO',
   },
   {
      row: 1,
      value: 'p',
      pressedShift: 'P',
      capsLocked: 'P',
      keycode: '80',
      code: 'KeyP',
   },
   {
      row: 1,
      value: '[',
      pressedShift: '{',
      capsLocked: '[',
      keycode: '219',
      code: 'BracketLeft',
   },
   {
      row: 1,
      value: ']',
      pressedShift: '}',
      capsLocked: ']',
      keycode: '221',
      code: 'BracketRight',
   },
   {
      row: 1,
      value: '\\',
      pressedShift: '|',
      capsLocked: '\\',
      keycode: '220',
      code: 'Backslash',
   },
   {
      row: 2,
      value: 'caps Lock',
      pressedShift: '',
      capsLocked: 'caps Lock',
      keycode: '20',
      code: 'CapsLock',
   },
   {
      row: 2,
      value: 'a',
      pressedShift: 'A',
      capsLocked: 'A',
      keycode: '65',
      code: 'KeyA',
   },
   {
      row: 2,
      value: 's',
      pressedShift: 'S',
      capsLocked: 'S',
      keycode: '83',
      code: 'KeyS',
   },
   {
      row: 2,
      value: 'd',
      pressedShift: 'D',
      capsLocked: 'D',
      keycode: '68',
      code: 'KeyD',
   },
   {
      row: 2,
      value: 'f',
      pressedShift: 'F',
      capsLocked: 'F',
      keycode: '70',
      code: 'KeyF',
   },
   {
      row: 2,
      value: 'g',
      pressedShift: 'G',
      capsLocked: 'G',
      keycode: '71',
      code: 'KeyG',
   },
   {
      row: 2,
      value: 'h',
      pressedShift: 'H',
      capsLocked: 'H',
      keycode: '72',
      code: 'KeyH',
   },
   {
      row: 2,
      value: 'j',
      pressedShift: 'J',
      capsLocked: 'J',
      keycode: '74',
      code: 'KeyJ',
   },
   {
      row: 2,
      value: 'k',
      pressedShift: 'K',
      capsLocked: 'K',
      keycode: '75',
      code: 'KeyK',
   },
   {
      row: 2,
      value: 'l',
      pressedShift: 'L',
      capsLocked: 'L',
      keycode: '76',
      code: 'KeyL',
   },
   {
      row: 2,
      value: ';',
      pressedShift: ':',
      capsLocked: ';',
      keycode: '186',
      code: 'Semicolon',
   },
   {
      row: 2,
      value: '\'',
      pressedShift: '"',
      capsLocked: '\'',
      keycode: '222',
      code: 'Quote',
   },
   {
      row: 2,
      value: 'return',
      pressedShift: '',
      capsLocked: 'return',
      keycode: '13',
      code: 'Enter',
   },
   {
      row: 3,
      value: `shift`,
      pressedShift: '',
      capsLocked: 'shift',
      keycode: '16',
      code: 'ShiftLeft',
   },
   {
      row: 3,
      value: 'z',
      pressedShift: 'Z',
      capsLocked: 'Z',
      keycode: '90',
      code: 'KeyZ',
   },
   {
      row: 3,
      value: 'x',
      pressedShift: 'X',
      capsLocked: 'X',
      keycode: '88',
      code: 'KeyX',
   },
   {
      row: 3,
      value: 'c',
      pressedShift: 'C',
      capsLocked: 'C',
      keycode: '67',
      code: 'KeyC',
   },
   {
      row: 3,
      value: 'v',
      pressedShift: 'V',
      capsLocked: 'V',
      keycode: '86',
      code: 'KeyV',
   },
   {
      row: 3,
      value: 'b',
      pressedShift: 'B',
      capsLocked: 'B',
      keycode: '66',
      code: 'KeyB',
   },
   {
      row: 3,
      value: 'n',
      pressedShift: 'N',
      capsLocked: 'N',
      keycode: '78',
      code: 'KeyN',
   },
   {
      row: 3,
      value: 'm',
      pressedShift: 'M',
      capsLocked: 'M',
      keycode: '77',
      code: 'KeyM',
   },
   {
      row: 3,
      value: ',',
      pressedShift: '<',
      capsLocked: ',',
      keycode: '188',
      code: 'Comma',
   },
   {
      row: 3,
      value: '.',
      pressedShift: '>',
      capsLocked: '.',
      keycode: '190',
      code: 'Period',
   },
   {
      row: 3,
      value: '/',
      pressedShift: '?',
      capsLocked: '/',
      keycode: '191',
      code: 'Slash',
   },
   {
      row: 3,
      value: 'shift',
      pressedShift: 'shift',
      capsLocked: 'shift',
      keycode: '16',
      code: 'ShiftRight',
   },
   {
      row: 4,
      value: 'fn',
      pressedShift: 'fn',
      capsLocked: 'fn',
      keycode: '0',
      code: 'Unidentified',
   },
   {
      row: 4,
      value: 'control',
      pressedShift: '',
      capsLocked: 'control',
      keycode: '17',
      code: 'ControlLeft',
   },
   {
      row: 4,
      value: 'option',
      pressedShift: '',
      capsLocked: 'option',
      keycode: '18',
      code: 'AltLeft',
   },
   {
      row: 4,
      value: 'command',
      pressedShift: '',
      capsLocked: 'command',
      keycode: '91',
      code: 'MetaLeft',
   },
   {
      row: 4,
      value: 'space',
      pressedShift: '',
      capsLocked: 'space',
      keycode: '32',
      code: 'Space',
   },
   {
      row: 4,
      value: 'command',
      pressedShift: '',
      capsLocked: 'command',
      keycode: '93',
      code: 'MetaRight',
   },
   {
      row: 4,
      value: 'option',
      pressedShift: '',
      capsLocked: 'option',
      keycode: '18',
      code: 'AltRight',
   },
   {
      row: 4,
      value: 'left',
      pressedShift: 'left',
      capsLocked: 'left',
      keycode: '37',
      code: 'ArrowLeft',
   },
   {
      row: 4,
      value: 'up',
      pressedShift: 'up',
      capsLocked: 'up',
      keycode: '38',
      code: 'ArrowUp',
   },
   {
      row: 4,
      value: 'down',
      pressedShift: 'down',
      capsLocked: 'down',
      keycode: '40',
      code: 'ArrowDown',
   },
   {
      row: 4,
      value: 'right',
      pressedShift: 'right',
      capsLocked: 'right',
      keycode: '39',
      code: 'ArrowRight',
   },
];



