//probably create one file with ruValue and enValue???
//add event.code?
export const englishKeyboardArray = [
   {
      row: 0,
      value: 'Esc',
      pressedShift: '',
      capsLocked: '',
      keycode: '27',
      code: '',
   },
   {
      row: 0,
      value: '`',
      pressedShift: '~',
      capsLocked: '',
      keycode: '48',
      code: '',
   },
   {
      row: 0,
      value: '1',
      pressedShift: '!',
      capsLocked: '',
      keycode: '49',
      code: '',
   },
   {
      row: 0,
      value: '2',
      pressedShift: '@',
      capsLocked: '',
      keycode: '50',
      code: '',
   },
   {
      row: 0,
      value: '3',
      pressedShift: '#',
      capsLocked: '',
      keycode: '51',
      code: '',
   },
   {
      row: 0,
      value: '4',
      pressedShift: '$',
      capsLocked: '',
      keycode: '52',
      code: '',
   },
   {
      row: 0,
      value: '5',
      pressedShift: '%',
      capsLocked: '',
      keycode: '53',
      code: '',
   },
   {
      row: 0,
      value: '6',
      pressedShift: '^',
      capsLocked: '',
      keycode: '54',
      code: '',
   },
   {
      row: 0,
      value: '7',
      pressedShift: '&',
      capsLocked: '',
      keycode: '55',
      code: '',
   },
   {
      row: 0,
      value: '8',
      pressedShift: '*',
      capsLocked: '',
      keycode: '56',
      code: '',
   },
   {
      row: 0,
      value: '9',
      pressedShift: '(',
      capsLocked: '',
      keycode: '57',
      code: '',
   },
   {
      row: 0,
      value: '0',
      pressedShift: ')',
      capsLocked: '',
      keycode: '48',
      code: '',
   },
   {
      row: 0,
      value: '-',
      pressedShift: '_',
      capsLocked: '',
      keycode: '189',
      code: '',
   },
   {
      row: 0,
      value: '=',
      pressedShift: '+',
      capsLocked: '',
      keycode: '187',
      code: '',
   },
   {
      row: 0,
      value: 'delete',
      pressedShift: '',
      capsLocked: '',
      keycode: '8',
      code: '',
   },
   {
      row: 1,
      value: 'Tab',
      pressedShift: '',
      capsLocked: '',
      keycode: '9',
      code: '',
   },
   {
      row: 1,
      value: 'q',
      pressedShift: 'Q',
      capsLocked: 'Q',
      keycode: '81',
      code: '',
   },
   {
      row: 1,
      value: 'w',
      pressedShift: 'W',
      capsLocked: 'W',
      keycode: '87',
      code: '',
   },
   {
      row: 1,
      value: 'e',
      pressedShift: 'E',
      capsLocked: 'E',
      keycode: '69',
      code: '',
   },
   {
      row: 1,
      value: 'r',
      pressedShift: 'R',
      capsLocked: 'R',
      keycode: '82',
      code: '',
   },
   {
      row: 1,
      value: 't',
      pressedShift: 'T',
      capsLocked: 'T',
      keycode: '84',
      code: '',
   },
   {
      row: 1,
      value: 'y',
      pressedShift: 'Y',
      capsLocked: 'Y',
      keycode: '89',
      code: '',
   },
   {
      row: 1,
      value: 'u',
      pressedShift: 'U',
      capsLocked: 'U',
      keycode: '85',
      code: '',
   },
   {
      row: 1,
      value: 'i',
      pressedShift: 'I',
      capsLocked: 'I',
      keycode: '73',
      code: '',
   },
   {
      row: 1,
      value: 'o',
      pressedShift: 'O',
      capsLocked: 'O',
      keycode: '79',
      code: '',
   },
   {
      row: 1,
      value: 'p',
      pressedShift: 'P',
      capsLocked: 'P',
      keycode: '80',
      code: '',
   },
   {
      row: 1,
      value: '[',
      pressedShift: '{',
      capsLocked: '',
      keycode: '219',
      code: '',
   },
   {
      row: 1,
      value: ']',
      pressedShift: '}',
      capsLocked: '',
      keycode: '221',
      code: '',
   },
   {
      row: 1,
      value: '\\',
      pressedShift: '|',
      capsLocked: '',
      keycode: '220',
      code: '',
   },
   {
      row: 2,
      value: 'caps Lock',
      pressedShift: '',
      capsLocked: '',
      keycode: '20',
      code: '',
   },
   {
      row: 2,
      value: 'a',
      pressedShift: 'A',
      capsLocked: 'A',
      keycode: '65',
      code: '',
   },
   {
      row: 2,
      value: 's',
      pressedShift: 'S',
      capsLocked: 'S',
      keycode: '83',
      code: '',
   },
   {
      row: 2,
      value: 'd',
      pressedShift: 'D',
      capsLocked: 'D',
      keycode: '68',
      code: '',
   },
   {
      row: 2,
      value: 'f',
      pressedShift: 'F',
      capsLocked: 'F',
      keycode: '70',
      code: '',
   },
   {
      row: 2,
      value: 'g',
      pressedShift: 'G',
      capsLocked: 'G',
      keycode: '71',
      code: '',
   },
   {
      row: 2,
      value: 'h',
      pressedShift: 'H',
      capsLocked: 'H',
      keycode: '72',
      code: '',
   },
   {
      row: 2,
      value: 'j',
      pressedShift: 'J',
      capsLocked: 'J',
      keycode: '74',
      code: '',
   },
   {
      row: 2,
      value: 'k',
      pressedShift: 'K',
      capsLocked: 'K',
      keycode: '75',
      code: '',
   },
   {
      row: 2,
      value: 'l',
      pressedShift: 'L',
      capsLocked: 'L',
      keycode: '76',
      code: '',
   },
   {
      row: 2,
      value: ';',
      pressedShift: ':',
      capsLocked: '',
      keycode: '186',
      code: '',
   },
   {
      row: 2,
      value: '\'',
      pressedShift: '"',
      capsLocked: '',
      keycode: '222',
      code: '',
   },
   {
      row: 2,
      value: 'return',
      pressedShift: '',
      capsLocked: '',
      keycode: '13',
      code: '',
   },
   {
      row: 3,
      value: `shift`,
      pressedShift: '',
      capsLocked: '',
      keycode: '16',
      code: '',
   },
   {
      row: 3,
      value: 'z',
      pressedShift: 'Z',
      capsLocked: 'Z',
      keycode: '90',
      code: '',
   },
   {
      row: 3,
      value: 'x',
      pressedShift: 'X',
      capsLocked: 'X',
      keycode: '88',
      code: '',
   },
   {
      row: 3,
      value: 'c',
      pressedShift: 'C',
      capsLocked: 'C',
      keycode: '67',
      code: '',
   },
   {
      row: 3,
      value: 'v',
      pressedShift: 'V',
      capsLocked: 'V',
      keycode: '86',
      code: '',
   },
   {
      row: 3,
      value: 'b',
      pressedShift: 'B',
      capsLocked: 'B',
      keycode: '66',
      code: '',
   },
   {
      row: 3,
      value: 'n',
      pressedShift: 'N',
      capsLocked: 'N',
      keycode: '78',
      code: '',
   },
   {
      row: 3,
      value: 'm',
      pressedShift: 'M',
      capsLocked: 'M',
      keycode: '77',
      code: '',
   },
   {
      row: 3,
      value: ',',
      pressedShift: '<',
      capsLocked: '',
      keycode: '188',
      code: '',
   },
   {
      row: 3,
      value: '.',
      pressedShift: '>',
      capsLocked: '',
      keycode: '190',
      code: '',
   },
   {
      row: 3,
      value: '/',
      pressedShift: '?',
      capsLocked: '',
      keycode: '191',
      code: '',
   },
   {
      row: 3,
      value: 'shift',
      pressedShift: '',
      capsLocked: '',
      keycode: '16',
      code: '',
   },
   {
      row: 4,
      value: 'fn',
      pressedShift: '',
      capsLocked: '',
      keycode: '0',
      code: 'Unidentified',
   },
   {
      row: 4,
      value: 'control',
      pressedShift: '',
      capsLocked: '',
      keycode: '17',
      code: '',
   },
   {
      row: 4,
      value: 'option',
      pressedShift: '',
      capsLocked: '',
      keycode: '18',
      code: '',
   },
   {
      row: 4,
      value: 'command',
      pressedShift: '',
      capsLocked: '',
      keycode: '91',
      code: 'MetaLeft',
   },
   {
      row: 4,
      value: 'space',
      pressedShift: '',
      capsLocked: '',
      keycode: '32',
      code: 'Space',
   },
   {
      row: 4,
      value: 'command',
      pressedShift: '',
      capsLocked: '',
      keycode: '93',
      code: 'MetaRight',
   },
   {
      row: 4,
      value: 'option',
      pressedShift: '',
      capsLocked: '',
      keycode: '18',
      code: '',
   },
   {
      row: 4,
      value: 'left',
      pressedShift: '',
      capsLocked: '',
      keycode: '37',
      code: '',
   },
   {
      row: 4,
      value: 'up',
      pressedShift: '',
      capsLocked: '',
      keycode: '38',
      code: '',
   },
   {
      row: 4,
      value: 'down',
      pressedShift: '',
      capsLocked: '',
      keycode: '40',
      code: '',
   },
   {
      row: 4,
      value: 'right',
      pressedShift: '',
      capsLocked: '',
      keycode: '39',
      code: '',
   },
];



