//probably create one file with ruValue and enValue???
//add event.code?
export const russianKeyboardArray = [
   {
      row: 0,
      value: 'Esc',
      pressedShift: '',
      capsLocked: '',
      keycode: '27',
      code: 'Escape',
   },
   {
      row: 0,
      value: ']',
      pressedShift: '[',
      capsLocked: ']',
      keycode: '48',
      code: 'Backquote',
   },
   {
      row: 0,
      value: '1',
      pressedShift: '!',
      capsLocked: '1',
      keycode: '49',
      code: 'Digit1',
   },
   {
      row: 0,
      value: '2',
      pressedShift: '"',
      capsLocked: '2',
      keycode: '50',
      code: 'Digit2',
   },
   {
      row: 0,
      value: '3',
      pressedShift: '№',
      capsLocked: '3',
      keycode: '51',
      code: 'Digit3',
   },
   {
      row: 0,
      value: '4',
      pressedShift: '%',
      capsLocked: '4',
      keycode: '52',
      code: 'Digit4',
   },
   {
      row: 0,
      value: '5',
      pressedShift: ':',
      capsLocked: '5',
      keycode: '53',
      code: 'Digit5',
   },
   {
      row: 0,
      value: '6',
      pressedShift: ',',
      capsLocked: '6',
      keycode: '54',
      code: 'Digit6',
   },
   {
      row: 0,
      value: '7',
      pressedShift: '.',
      capsLocked: '7',
      keycode: '55',
      code: 'Digit7',
   },
   {
      row: 0,
      value: '8',
      pressedShift: ';',
      capsLocked: '8',
      keycode: '56',
      code: 'Digit8',
   },
   {
      row: 0,
      value: '9',
      pressedShift: '(',
      capsLocked: '9',
      keycode: '57',
      code: 'Digit9',
   },
   {
      row: 0,
      value: '0',
      pressedShift: ')',
      capsLocked: '0',
      keycode: '48',
      code: 'Digit0',
   },
   {
      row: 0,
      value: '-',
      pressedShift: '_',
      capsLocked: '-',
      keycode: '189',
      code: 'Minus',
   },
   {
      row: 0,
      value: '=',
      pressedShift: '+',
      capsLocked: '=',
      keycode: '187',
      code: 'Equal',
   },
   {
      row: 0,
      value: 'delete',
      pressedShift: '',
      capsLocked: 'delete',
      keycode: '8',
      code: 'Backspace',
   },
   {
      row: 1,
      value: 'Tab',
      pressedShift: 'Tab',
      capsLocked: '',
      keycode: '9',
      code: 'Tab',
   },
   {
      row: 1,
      value: 'й',
      pressedShift: 'Й',
      capsLocked: 'Й',
      keycode: '81',
      code: 'KeyQ',
   },
   {
      row: 1,
      value: 'ц',
      pressedShift: 'Ц',
      capsLocked: 'Ц',
      keycode: '87',
      code: 'KeyW',
   },
   {
      row: 1,
      value: 'у',
      pressedShift: 'У',
      capsLocked: 'У',
      keycode: '69',
      code: 'KeyE',
   },
   {
      row: 1,
      value: 'к',
      pressedShift: 'К',
      capsLocked: 'К',
      keycode: '82',
      code: 'KeyR',
   },
   {
      row: 1,
      value: 'е',
      pressedShift: 'Е',
      capsLocked: 'Е',
      keycode: '84',
      code: 'KeyT',
   },
   {
      row: 1,
      value: 'н',
      pressedShift: 'Н',
      capsLocked: 'Н',
      keycode: '89',
      code: 'KeyY',
   },
   {
      row: 1,
      value: 'г',
      pressedShift: 'Г',
      capsLocked: 'Г',
      keycode: '85',
      code: 'KeyU',
   },
   {
      row: 1,
      value: 'ш',
      pressedShift: 'Ш',
      capsLocked: 'Ш',
      keycode: '73',
      code: 'KeyI',
   },
   {
      row: 1,
      value: 'щ',
      pressedShift: 'Щ',
      capsLocked: 'Щ',
      keycode: '79',
      code: 'KeyO',
   },
   {
      row: 1,
      value: 'з',
      pressedShift: 'З',
      capsLocked: 'З',
      keycode: '80',
      code: 'KeyP',
   },
   {
      row: 1,
      value: 'х',
      pressedShift: 'Х',
      capsLocked: 'Х',
      keycode: '219',
      code: 'BracketLeft',
   },
   {
      row: 1,
      value: 'ъ',
      pressedShift: 'Ъ',
      capsLocked: 'Ъ',
      keycode: '221',
      code: 'BracketRight',
   },
   {
      row: 1,
      value: '\\',
      pressedShift: '/',
      capsLocked: '\\',
      keycode: '220',
      code: 'Backslash',
   },
   {
      row: 2,
      value: 'caps Lock',
      pressedShift: '',
      capsLocked: '',
      keycode: '20',
      code: 'CapsLock',
   },
   {
      row: 2,
      value: 'ф',
      pressedShift: 'Ф',
      capsLocked: 'Ф',
      keycode: '65',
      code: 'KeyA',
   },
   {
      row: 2,
      value: 'ы',
      pressedShift: 'Ы',
      capsLocked: 'Ы',
      keycode: '83',
      code: 'KeyS',
   },
   {
      row: 2,
      value: 'в',
      pressedShift: 'В',
      capsLocked: 'В',
      keycode: '68',
      code: 'KeyD',
   },
   {
      row: 2,
      value: 'а',
      pressedShift: 'А',
      capsLocked: 'А',
      keycode: '70',
      code: 'KeyF',
   },
   {
      row: 2,
      value: 'п',
      pressedShift: 'П',
      capsLocked: 'П',
      keycode: '71',
      code: 'KeyG',
   },
   {
      row: 2,
      value: 'р',
      pressedShift: 'Р',
      capsLocked: 'Р',
      keycode: '72',
      code: 'KeyH',
   },
   {
      row: 2,
      value: 'о',
      pressedShift: 'О',
      capsLocked: 'О',
      keycode: '74',
      code: 'KeyJ',
   },
   {
      row: 2,
      value: 'л',
      pressedShift: 'Л',
      capsLocked: 'Л',
      keycode: '75',
      code: 'KeyK',
   },
   {
      row: 2,
      value: 'д',
      pressedShift: 'Д',
      capsLocked: 'Д',
      keycode: '76',
      code: 'KeyL',
   },
   {
      row: 2,
      value: 'ж',
      pressedShift: 'Ж',
      capsLocked: 'Ж',
      keycode: '186',
      code: 'Semicolon',
   },
   {
      row: 2,
      value: 'э',
      pressedShift: 'Э',
      capsLocked: 'Э',
      keycode: '222',
      code: 'Quote',
   },
   {
      row: 2,
      value: 'return',
      pressedShift: '',
      capsLocked: '',
      keycode: '13',
      code: 'Enter',
   },
   {
      row: 3,
      value: `shift`,
      pressedShift: '',
      capsLocked: '',
      keycode: '16',
      code: 'ShiftLeft',
   },
   {
      row: 3,
      value: 'я',
      pressedShift: 'Я',
      capsLocked: 'Я',
      keycode: '90',
      code: 'KeyZ',
   },
   {
      row: 3,
      value: 'ч',
      pressedShift: 'Ч',
      capsLocked: 'Ч',
      keycode: '88',
      code: 'KeyX',
   },
   {
      row: 3,
      value: 'с',
      pressedShift: 'С',
      capsLocked: 'С',
      keycode: '67',
      code: 'KeyC',
   },
   {
      row: 3,
      value: 'м',
      pressedShift: 'М',
      capsLocked: 'М',
      keycode: '86',
      code: 'KeyV',
   },
   {
      row: 3,
      value: 'и',
      pressedShift: 'И',
      capsLocked: 'И',
      keycode: '66',
      code: 'KeyB',
   },
   {
      row: 3,
      value: 'т',
      pressedShift: 'Т',
      capsLocked: 'Т',
      keycode: '78',
      code: 'KeyN',
   },
   {
      row: 3,
      value: 'ь',
      pressedShift: 'Ь',
      capsLocked: 'Ь',
      keycode: '77',
      code: 'KeyM',
   },
   {
      row: 3,
      value: 'б',
      pressedShift: 'Б',
      capsLocked: 'Б',
      keycode: '188',
      code: 'Comma',
   },
   {
      row: 3,
      value: 'ю',
      pressedShift: 'Ю',
      capsLocked: 'Ю',
      keycode: '190',
      code: 'Period',
   },
   {
      row: 3,
      value: '/',
      pressedShift: '?',
      capsLocked: '/',
      keycode: '191',
      code: 'Slash',
   },
   {
      row: 3,
      value: 'shift',
      pressedShift: '',
      capsLocked: 'shift',
      keycode: '16',
      code: 'ShiftRight',
   },
   {
      row: 4,
      value: 'fn',
      pressedShift: 'fn',
      capsLocked: 'fn',
      keycode: '0',
      code: 'Unidentified',
   },
   {
      row: 4,
      value: 'control',
      pressedShift: 'control',
      capsLocked: 'control',
      keycode: '17',
      code: 'ControlLeft',
   },
   {
      row: 4,
      value: 'option',
      pressedShift: 'option',
      capsLocked: 'option',
      keycode: '18',
      code: 'AltLeft',
   },
   {
      row: 4,
      value: 'command',
      pressedShift: 'command',
      capsLocked: 'command',
      keycode: '91',
      code: 'MetaLeft',
   },
   {
      row: 4,
      value: 'space',
      pressedShift: '',
      capsLocked: '',
      keycode: '32',
      code: 'Space',
   },
   {
      row: 4,
      value: 'command',
      pressedShift: '',
      capsLocked: '',
      keycode: '93',
      code: 'MetaRight',
   },
   {
      row: 4,
      value: 'option',
      pressedShift: '',
      capsLocked: '',
      keycode: '18',
      code: 'AltRight',
   },
   {
      row: 4,
      value: 'left',
      pressedShift: '',
      capsLocked: '',
      keycode: '37',
      code: 'ArrowLeft',
   },
   {
      row: 4,
      value: 'up',
      pressedShift: '',
      capsLocked: '',
      keycode: '38',
      code: 'ArrowUp',
   },
   {
      row: 4,
      value: 'down',
      pressedShift: '',
      capsLocked: '',
      keycode: '40',
      code: 'ArrowDown',
   },
   {
      row: 4,
      value: 'right',
      pressedShift: '',
      capsLocked: '',
      keycode: '39',
      code: 'ArrowRight',
   },
];



